resources:
- policy.open-cluster-management.io_operatorpolicies.yaml

patches:
# The OperatorPolicy has fewer allowed ComplianceTypes than ConfigurationPolicy
- path: allowed-compliance-types.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: operatorpolicies.policy.open-cluster-management.io
