apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  labels:
    cluster-name: local-cluster
    cluster-namespace: local-cluster
    policy.open-cluster-management.io/cluster-name: local-cluster
    policy.open-cluster-management.io/cluster-namespace: local-cluster
    policy.open-cluster-management.io/policy: open-cluster-management-global-set.jk-gitops-op
  name: install-gitops-operator
spec:
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: high
  subscription:
    name: openshift-gitops-operator
  upgradeApproval: Automatic
